import { ProjectCardProps } from '@/components/ui/project-card/project-card.tsx';

export const ProjectCards: ProjectCardProps[] = [
    {
        id: 'rokr-ai',
        title: 'ROKR AI',
        date: '2024-PRESENT',
        hasIcon: false,
        iconUrl: '',
        iconType: 'Github',
        projectType: 'Work',
        description: `A project with the intent of researching and implementing various use cases using LLM models (such as OpenAI, AWS Titan, Claude, etc.) in the augmentation of an OKR management platform. The team has a workflow on both implementation and testing of the use cases through development of a playground application and creating comparative analysis on various LLM topics (e.g.: RAG)`,
        involvement: `I bear the primary responsibility for the architectural design and research on various subjects, as well as managing the AWS cloud infrastructure using the CDK.`,
        tags: [
            'AWS Lambda',
            'AWS CDK',
            'AWS Services',
            'Serverless',
            'Angular',
            'JavaScript',
            'TypeScript',
            'Sass',
            'Storybook',
            'Ngrx',
            'Redux',
            'ESBuild',
            'DynamoDB',
            'Nx',
            'LLM',
            'LangChain',
            'OpenAI',
            'HTML',
            'CSS'
        ]
    },
    {
        id: 'ubb-citizen-science',
        title: 'UBB Citizen Science',
        date: '2023-2024',
        hasIcon: true,
        iconUrl: 'https://citizenscience.openscience.ubbcluj.ro/',
        iconType: 'Website',
        projectType: 'Work',
        description: `An online platform that Babeș-Bolyai University aims to showcase its projects that involve citizens in a comprehensive and accessible manner. Citizens have the opportunity to select projects of interest and find simple and efficient tools to get involved, expressing long-term interest so they can be efficiently contacted whenever new relevant projects emerge.`,
        involvement: `I participated in this project for a set period to assist in advancing it to the production phase. My role involved full-stack development duties, with a focus on refining and improving challenging aspects of the application, including functionality, JPA query optimization, and enhancing overall code cleanliness and quality.`,
        tags: [
            'Spring',
            'Angular',
            'Java',
            'JavaScript',
            'TypeScript',
            'Sass',
            'Storybook',
            'Ngrx',
            'Redux',
            'Docker',
            'Postgres',
            'Nx',
            'Azure',
            'HTML',
            'CSS'
        ]
    },
    {
        id: 'eam-tool',
        title: 'EAM Tool',
        date: '2023',
        hasIcon: false,
        iconUrl: '',
        iconType: 'Github',
        projectType: 'Work',
        description: `An application designed for managing sales leads within a hierarchical organizational structure, which also requires the importation of extensive external data from various Excel files.`,
        involvement: `I worked as the lead frontend developer for this project, handling the structure, rules and development on that side of the project, including the responsive design. Furthermore, I participated in the wide architecture and infrastructure decisions of the project.`,
        tags: [
            'Spring',
            'Angular',
            'Kotlin',
            'JavaScript',
            'TypeScript',
            'Storybook',
            'Ngrx',
            'Redux',
            'Docker',
            'Nx',
            'AWS Services',
            'Terraform',
            'Github Actions',
            'Postgres',
            'HTML',
            'CSS',
            'Sass',
            'Material Design'
        ]
    },
    {
        id: 'decentralized-freelance-news',
        title: 'Decentralized Freelance News',
        date: '2023',
        hasIcon: true,
        iconUrl:
            'https://github.com/antonio-marasescu/decentralized-freelance-news',
        iconType: 'Github',
        projectType: 'Personal',
        description: `The master's thesis application which is centered on creating an open news platform that ensures the verifiability of writers' identities using Zero-Knowledge Proofs.`,
        involvement: `This project was structured as a series of mini-applications, with one module dedicated to managing identity proofs and another responsible for operating the decentralized news website, which interfaces with the Ethereum network.`,
        tags: [
            'NestJs',
            'Angular',
            'Solidity',
            'JavaScript',
            'TypeScript',
            'Ngrx',
            'Redux',
            'Nx',
            'TypeOrm',
            'Ethereum',
            'Zero-Knowledge Proofs',
            'Docker',
            'Postgres',
            'HTML',
            'CSS',
            'Sass',
            'Truffle'
        ]
    },
    {
        id: 'roadmap-architect',
        title: 'Roadmap Architect',
        date: '2022-2023',
        hasIcon: false,
        iconUrl: '',
        iconType: 'Github',
        projectType: 'Work',
        description: `An internal project intended to be used as a roadmap creator and viewer for the company's training programs, enabling the display of graph-like roadmaps with links to markdown files hosted on Github`,
        involvement: `I played a pivotal role in the proposal, implementation, and deployment of the functionality, and I am currently one of the maintainers.`,
        tags: [
            'React',
            'JavaScript',
            'TypeScript',
            'Nx',
            'Github Actions',
            'HTML',
            'CSS',
            'Sass',
            'Material Design'
        ]
    },
    {
        id: 'lotus-insurance',
        title: 'Lotus Insurance',
        date: '2023',
        hasIcon: false,
        iconUrl: '',
        iconType: 'Github',
        projectType: 'Work',
        description: `A multi-party contract negotiation platform for the insurance and reinsurance business, that featured fully segregated data multi-tenancy and managing the workflow of a policy and its contracts.`,
        involvement: `Engaged in full-stack development for the application, including architecting the multi-tenancy solution.`,
        tags: [
            'Spring',
            'React',
            'Kotlin',
            'JavaScript',
            'TypeScript',
            'Storybook',
            'Ngrx',
            'Redux',
            'Docker',
            'Nx',
            'AWS Services',
            'Terraform',
            'Github Actions',
            'Cypress',
            'Postgres',
            'Multi-tenancy',
            'HTML',
            'CSS',
            'Sass',
            'Material Design'
        ]
    },
    {
        id: 'b3i-corda-solutions',
        title: 'B3I Corda Projects',
        date: '2021-2023',
        hasIcon: false,
        iconUrl: '',
        iconType: 'Github',
        projectType: 'Work',
        description: `Various sub-projects developed with the intent of offering the automation of the insurance and reinsurance workflow through a permissioned blockchain Corda to various companies.`,
        involvement: `I contributed comprehensively to the development process, with a pronounced emphasis on frontend. My involvement spanned the initiation of various sub-projects, where I concentrated on their development and progression`,
        tags: [
            'Spring',
            'Angular',
            'NestJs',
            'Kotlin',
            'JavaScript',
            'TypeScript',
            'Storybook',
            'Docker',
            'Nx',
            'Postgres',
            'Cypress',
            'Ngrx',
            'Redux',
            'Gitlab',
            'Corda',
            'HTML',
            'CSS',
            'Sass',
            'Material Design'
        ]
    },
    {
        id: 'edublock',
        title: 'Edublock',
        date: '2021',
        hasIcon: true,
        iconUrl: 'https://github.com/antonio-marasescu/EduBlock',
        iconType: 'Github',
        projectType: 'Personal',
        description: `A self-made private blockchain platform intended for the sharing of educational records between universities. It was created to serve as my bachelor thesis degree`,
        involvement: `This project was designed to organize multiple APIs that interact during transaction processing with various worker nodes, and to manage and orchestrate communication via a message broker. Moreover, it implements the initial the proof-of-work algorithm and other blockchain concepts to validate functionality.`,
        tags: [
            'ExpressJs',
            'Angular',
            'JavaScript',
            'TypeScript',
            'Ngrx',
            'Redux',
            'TypeOrm',
            'Docker',
            'Postgres',
            'HTML',
            'CSS',
            'Sass',
            'Gulp'
        ]
    },
    {
        id: 'dipko',
        title: 'Dipko',
        date: '2019-2021',
        hasIcon: false,
        iconUrl: '',
        iconType: 'Github',
        projectType: 'Work',
        description: `An application for ticketing and promotions offered by energy companies in Germany..`,
        involvement: `Contributed to the development of a full-stack application, employing Node.js (Express.js), GraphQL, Angular, Postgres, Redis and AWS, implementing features across all facets of the application`,
        tags: [
            'Angular',
            'ExpressJs',
            'JavaScript',
            'TypeScript',
            'Docker',
            'GraphQl',
            'Ngrx',
            'Redux',
            'TypeORM',
            'Cypress',
            'DynamoDB',
            'Redis',
            'Jest',
            'HTML',
            'CSS',
            'Sass'
        ]
    },
    {
        id: 'ethereum-cv-sharepoint',
        title: 'CV Sharepoint',
        date: '2020',
        hasIcon: true,
        iconUrl: 'https://github.com/antonio-marasescu/Ethereum-CV-Sharepoint',
        iconType: 'Github',
        projectType: 'Personal',
        description: `An introductory application to using Ethereum with Angular, Truffle, Ganache and IPFS. It will represent a sharepoint for saving and sharing files (in our case CV's) onto the blockchain. More specifically storing their hash in the contract and saving the actual file onto IPFS.`,
        involvement: ``,
        tags: [
            'Angular',
            'Solidity',
            'JavaScript',
            'TypeScript',
            'HTML',
            'CSS',
            'Sass',
            'IPFS',
            'Truffle'
        ]
    }
];
