name: Publish

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Configure Credentials
        uses: aws-action/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ vars.AWS_IAM }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Install dependencies
        run: npm ci
      - name: Build sources
        run: npm run build
      - name: Publish website
        run: aws s3 sync ./dist s3://${{ vars.AWS_BUCKET_NAME }}
      - name: Invalidate Cloudfront
        run: aws cloudfront create-invalidation --distribution-id ${{ vars.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
