name: Quality Check

on:
  push:
    branches:
      - '**' # Matches all branches

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Prettier Check
        run: pnpm run prettier:check
      - name: Lint
        run: pnpm run lint
      - name: Build sources
        run: pnpm run build
